#!/bin/sh
# Copyright David Shin 2016
# 
# Takes input file with a single column (multiple rows) of data
# Outputs as a single comma-delimited line to stdout
#
# Usage ./rows2csv <filename> 

awk '{print $1 ","}' $1 |  tr -d '\n'    # no space after comma
